/*
============================================================================================
DDL Script: Create Bronze Tables
============================================================================================
Script Purpose:
    This script creates table in the 'bronze' schema, dropping existing tables
    if they already exist
  Run this script to re-define the DDL structure of 'bronze' Tables
=============================================================================================
*/
